name: Aggiorna Menu

on:
  workflow_dispatch:   # permette di far partire l'azione manualmente
  push:
    paths:
      - 'menu/menuData.json'  # reagisce se cambi il JSON nel repo

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit JSON aggiornato
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add menu/menuData.json
          git commit -m "Aggiornamento automatico menu via workflow" || echo "Nessuna modifica"
          git push
